services:
  intouch.mvc:
    image: ${DOCKER_REGISTRY-}intouchmvc
    build:
      context: .
      dockerfile: InTouch.MVC/Dockerfile
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=intouchdb;Username=postgres;Password=InTouch228
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_HTTPS_PORT=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/webapp.chained.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/app/certs/webapp.key
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - app-network
    volumes:
      - keys:/app/keys:rw
      - ./certs/webapp.chained.crt:/app/certs/webapp.chained.crt:ro
      - ./certs/webapp.key:/app/certs/webapp.key:ro

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=InTouch228
      - POSTGRES_DB=intouchdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:
  keys:

networks:
  app-network:
    driver: bridge